### ISSUE TITLE
Do you have examples using SWIFT ?

### ISSUE THREAD

**Issue by Glagnar** [gonzalezreal/Groot#10]
This is just a thought, but perhaps you could provide examples of Groot being used in a SWIFT environment. Especially if there are any caveats.

**Comment by gonzalezreal** [comment]
There shouldn't be any caveat. As soon as I have some time I will work on the examples. Thanks for the suggestion!

**Comment by Glagnar** [comment]
Thanks, I think a lot of people would appreciate that.

**Comment by gonzalezreal** [comment]
@Glagnar Groot is being re-implemented using Swift. You can check the [swift](https://github.com/gonzalezreal/Groot/tree/swift) branch, more specifically [GrootTest.swift](https://github.com/gonzalezreal/Groot/blob/swift/GrootTests/GrootTests.swift) for usage examples in Swift.
