### ISSUE TITLE
Composite primary key

### ISSUE THREAD

**Issue by Glagnar** [gonzalezreal/Groot#11]
I have a simplified scenario with two tables in a one to many relationship. Each table has one column called 'Name':
Parent ---< Child

Let us say we want the Parent.name to be unique - which is easy.
We also want a Child.name to be unique for a parent, ie. a composite key. How do I implement this  ?
( This assumes that no parent will ever give the same name to two children )

**Comment by gonzalezreal** [comment]
I think the only way to handle this scenario is to have the parent's name in each child:

```json
{
	"name": "Foo",
	"children": [
		{
			"parentName": "Foo",
			"name": "Bar"
		},
		...
	]
}
```

And use the `identityAttributes` [annotation](https://github.com/gonzalezreal/Groot/blob/master/Documentation/Annotations.md#identityattributes) on the **child entity** with a value of `parentName, name`.
