### ISSUE TITLE
CoreData abstract entity and inheritance

### ISSUE THREAD

**Issue by matteomosca** [gonzalezreal/Groot#12]
In my coredata DB there are concrete object B, C, D, that inherit from another abstract object A.
Another object C has a relationship with A, that at runtime could be B, C, D.

During the unmarshaling (NSDictionary -> NSManagedObject) what entity does groot recognize? A or B/C/D?

**Comment by bill350** [comment]
Hi,
Same question here, it appears that Groot does not manage Abstract Entities.

**Comment by matteomosca** [comment]
No way, it doesn't manage Abstract Entities...

**Comment by gonzalezreal** [comment]
Hi there,

Support for entity inheritance has been implemented in #28 and it is currently available in https://github.com/gonzalezreal/Groot/tree/1.0
