### ISSUE TITLE
Add Documentation / User Guide

### ISSUE THREAD

**Issue by AliSoftware** [gonzalezreal/Groot#17]
I believe that at some point there were some wiki pages but they seem to have disappeared?

Anyway, I love Groot but it really lack proper documentation. The README gave some info, but not enough. Like:

 * What are the name of the userInfo keys that can be used (an exhaustive list should be available)
 * How do I ignore a field (document that you can use a `JSONKeyPath` = `null` for that)
 * Document what is supported and what isn't (Abstract entities, etc)
 * Document the KeyPath usage in depth (reassure the reader that using a KeyPath for reading the JSON into a ManagedObject also works the other way around, when you translate your NSMO to JSON it creates the intermediate dictionary, etc)
 * and I'm sure that there is much more questions to be answered that I don't think about right away

Having a README with some "QuickStart" & examples is great, but not as useful as a complete documentation. I think the wiki may be a nice place for that so that it can be easily editable and updatable (from anyone who wishes to contribute as well).

**Comment by gonzalezreal** [comment]
I will most definitely work on improving the documentation. Your bullet points are most valuable, thanks for the feedback!

**Comment by gonzalezreal** [comment]
I have updated the documentation for Groot 1.0. If you think something is missing please re-open and we can discuss it.
