### ISSUE TITLE
Relationship without embeeded models?

### ISSUE THREAD

**Issue by jeryTymate** [gonzalezreal/Groot#18]
How can I manage the fact that I can only have the relationships in 2 requests, instead of one?
For example, using characters and publishers model, I would have: http://myapi/characters.json which gives me the list of characters ; And http://myapi/publishers.json which gives me the list of publishers.

And in the characters.json, for each character, have a key: "publisher_id": xxx (contrary to your example, where the publisher is embedded in the character.json.

How can I make Groot to build the relationship between characters and its publisher, if publishers are fetched in another request?

Sincerely,

Jery

**Comment by gonzalezreal** [comment]
We are working on that. See #15.

**Comment by jeryTymate** [comment]
Nice :)

**Comment by gonzalezreal** [comment]
This functionality has been implemented in #26 and it is currently available in [branch 1.0](https://github.com/gonzalezreal/Groot/tree/1.0) just in case you want to try it.
