### ISSUE TITLE
Unable to read the license file, Cocoapods

### ISSUE THREAD

**Issue by Lolloz89** [gonzalezreal/Groot#35]
When installing the pod I get this error message:

Unable to read the license file `/Users/.../Pods/Groot/LICENSE` for the spec `Groot (1.0)`

No Groot source file is downloaded.

**Comment by gonzalezreal** [comment]
Thanks for reporting this! I just updated the pod spec, and released a new version (1.0.1). It should be working now.

**Comment by Lolloz89** [comment]
Thank you too, now it’s all working properly. 
The only thing is that I had to specify '~> 1.0.1' on the podfile, otherwise it still didn’t work.

Lorenzo
