### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by carguezu** [gonzalezreal/Groot#36]
I know iOS 9 is still in beta, but there is some errors while compailing under Xcode 7 beta4.

**Comment by gonzalezreal** [comment]
Are those Swift 2 related errors?

**Comment by carguezu** [comment]
I'm not sure since the compiler doesn't give me more details, but for example:

![screen shot 2015-07-22 at 18 21 57](https://cloud.githubusercontent.com/assets/4050713/8830867/ed9e8dd0-309e-11e5-8c54-dd10a15ea25b.png)

**Comment by gonzalezreal** [comment]
Yes, that is Swift 2.0 related, which currently is not related. I'm renaming the issue. Thanks for reporting!

**Comment by carguezu** [comment]
thank you for the support and fast responding

**Comment by markkrenek** [comment]
Has anyone converted this to Swift 2.0 yet? My project is already Swift 2.0 and I really want to use Groot. I've started my own conversion, but thought I'd ask.

**Comment by gonzalezreal** [comment]
I was planning to do it in the following weeks. Should be fairly simple. But PRs are welcome...

**Comment by gonzalezreal** [comment]
Done :smile:. Please add any comments or suggestions to #49. You can also try it via Cocoapods using:

```
pod 'Groot', :git => 'https://github.com/gonzalezreal/Groot.git', :branch => 'swift_2'
```

Your feedback is welcome.
