### ISSUE TITLE
Groot is very useful .But i have a problem！！

### ISSUE THREAD

**Issue by huangqiaobo** [gonzalezreal/Groot#37]
several months ago , i found Groot . (maybe is 0.2 version ，i don't remember clearly).
groot is very useful with coredata .
but , i found the lastest verson is very troublesome.
i should must creat JSONKeyPath for every attribute in entity , even if the attribute name is the same as in json , and even if the attribute dont need to transform back to json .

i just still have no clue, why you would do so . 
just to transform json from coredata ?
in what case, transform json from coredata will be very useful ?

**Comment by gonzalezreal** [comment]
Hi @huangqiaobo,

Yes, one of the breaking changes we decided to make for version 1.0 is to make JSON key path mapping explicit: Attributes and relationships that don't have a `JSONKeyPath` entry are not considered for JSON serialization or deserialization. This makes easier to have other attributes in the managed object that are not related with the JSON (the `JSONKeyPath=null` solution was a bit contrived).

Unfortunately we couldn't find a good way to make the transition to explicit JSON key paths easier (we are still thinking about it). If this is a big issue for you, I suggest you go back to version 0.2 in the meantime.

You can check the [JSONKeyPath](https://github.com/gonzalezreal/Groot/blob/master/Documentation/Annotations.md#JSONKeyPath) documentation for more information.

**Comment by huangqiaobo** [comment]
HI @gonzalezreal ，

Thank you for your reply.
I discussed it with my colleagues. At last, I let the groot go back to version 0.2. Because , most of the time , we don't need to change NSManagedObject object back to json in our iOS project. And the attributes name in entity always is the same as in json.

You known, it's troublesome to chosen a name for a property. So, we always use the name in json which get from server, and it is easier to maintenance.

: )
