### ISSUE TITLE
Polymorphic relationships

### ISSUE THREAD

**Issue by soulchild** [gonzalezreal/Groot#41]
I have a JSON blob like this:

    [
        { 
            "id": 1,
            "title": "Audio Title",
            "type": "audio",
        },
        {
            "id": 2,
            title: "Video Title",
            type: "video",
        }
    ]

I'm no Core Data expert, but I suppose it's possible to have a common Media base class entity with two entity subclasses for Video and Audio objects? If so, do you think Groot will be able to correctly deserialize the JSON blob above into Video and Audio object entities respectively based on the type property?

Thanks!

**Comment by gonzalezreal** [comment]
Yes, this use case is supported by Groot. Check the [Annotations.md](https://github.com/gonzalezreal/Groot/blob/master/Documentation/Annotations.md) doc. `entityMapperName` is what you're looking for.

**Comment by soulchild** [comment]
Awesome, thanks!

**Comment by soulchild** [comment]
Hmm ... Somehow my entity mapper is not being picked up. I placed some breakpoints inside my `grt_setEntityMapperWithName:mapBlock:` block which isn't executed and from there traced my way back to `NSEntityDescription+Groot`, but the `grt_entityMapper` method is never reached. 

Diving deeper, I realized that `grt_valueForJSONValue` is not getting called because managedObject is not nil inside `grt_managedObjectForJSONValue:inContext:existingObjects:`.

My final (abbreviated) JSON looks like this:

    [
        {
            id: 1,
            title: "My Category",
            media: [
                {
                    id: 1,
                    title: "Audio",
                    type: "audio"
                },{
                    id: 2,
                    title: "Video",
                    type: "video"
                }
            ]
        }
    ]

So there are MediaCategory entities holding Media entities which can be either of type MediaAudio or MediaVideo. Here's the corresponding Core Data model:

![coredatamodel](https://cloud.githubusercontent.com/assets/59642/9135220/713c722e-3d0b-11e5-8498-c87d2382d332.png)

This is my entityMapper definition:

    [NSValueTransformer grt_setEntityMapperWithName:@"MediaTypeMapper"
                                           mapBlock:^NSString *(NSDictionary *JSONDictionary) {
                                               NSDictionary *entityMapping = @{
                                                                               @"video": @"MediaVideo",
                                                                               @"audio": @"MediaAudio"
                                                                               };
                                               NSString *type = JSONDictionary[@"type"];
                                               return entityMapping[type];
                                           }];

Fetching all MediaCategory entities and accessing the media property (which is supposed to fault either MediaAudio or MediaVideo entities) I'm getting:

    My Category: Relationship 'media' fault on managed object (0x7fd321db31d0) <MediaCategory: 0x7fd321db31d0> (entity: MediaCategory; id: 0xd000000000040000 <x-coredata://E5CE091C-ABB5-46E1-A310-0B91C5DC5084/MediaCategory/p1> ; data: {
    identifier = 1;
    media = "<relationship fault: 0x7fd321e94230 'media'>";
    title = My Category;
    })

Any ideas? Thanks a lot!

**Comment by soulchild** [comment]
Ah nevermind, I forgot the ```JSONKeyPath``` attribute for the ```media``` relationship from MediaCategory to Media. ;-)
