### ISSUE TITLE
Useless in a loop Core Data Model

### ISSUE THREAD

**Issue by Prometheuser** [gonzalezreal/Groot#46]
If my model have the relationship like below:

![image](https://cloud.githubusercontent.com/assets/13377095/9487998/1d20f946-4c09-11e5-9c19-26c42b19bbde.png)

(Don't focus on any other relationship except the red one)

In this situation, your code will crash. 

And i cannot figure out it.  Please fix it.

Thanks a lot!!!

**Comment by gonzalezreal** [comment]
Hi there,

Could you please provide more information about the crash? Call stack, debug output or ideally a sample project reproducing it would be of great help.

Thanks.

**Comment by gonzalezreal** [comment]
Closing as there is no feedback. Feel free to re-open if there is more information.
