### ISSUE TITLE
Preserving order

### ISSUE THREAD

**Issue by scriptease** [gonzalezreal/Groot#53]
Hello,

first of all thanks for the great project! 

I have a question, is it somehow possible to preserve the order in the json?
Since core data only provides sets it would be great to e.g. set an index in the relationship.

Is something like that possible?

Kind regards,
Florian

**Comment by ManueGE** [comment]
In these cases I just set the relationship as `ordered` in the model. Then it is parsed as `NSOrderedSet` and the JSON order is preserved.

**Comment by scriptease** [comment]
Thanks, that works for relations :-), and for a list of root objects i just set the index manually!
