### ISSUE TITLE
Non modular header error

### ISSUE THREAD

**Issue by aChase55** [gonzalezreal/Groot#57]
Getting a non-modular header error after installing groot pod and adding to objective-c project 
<img width="846" alt="screen shot 2015-11-17 at 3 44 52 pm" src="https://cloud.githubusercontent.com/assets/1834258/11228566/53add860-8d42-11e5-9ad7-88ee9714652c.png">

**Comment by gonzalezreal** [comment]
Hi, this is a Cocoapods issue. Please check #55 for possible workarounds.
