### ISSUE TITLE
Merging with deletion

### ISSUE THREAD

**Issue by soulchild** [gonzalezreal/Groot#6]
After evaluating tons of Core Data wrappers and object mappers I came across Groot and I'm really happy with its simplicity and approach.

My application has a one-way connection (so it's read-only) to a REST API to display some sort of news feed. I'm currently using the mergeObjectsForEntityName method to update my local Core Data store with data from the API. As expected, this does NOT remove items from Core Data which are no longer in the server's response. Is this a feature which could be incorporated into Groot or can you suggest a way of implementing this in my own code? I don't want to wipe out my whole Core Data entity and use insertObjectsForEntityName because my entities store additional meta data. 

Thanks! :)

**Comment by soulchild** [comment]
I just realized that the code you provided only works on the top level entity. For instance, take the following JSON structure (mapped to `Category` and `Item` Core Data entities):

    [
      {
        id: 1,
        title: "Category",
        items: [
          {
            id: 1,
            title: "Item #1"
          },
          {
            id: 2,
            title: "Item #2"
          }
        ]
      }
    ]

Now, when fetching all `Category` entities which have a too-many relationship with `Item` entities via `items`, and one of the items is removed from the JSON, it is not deleted from my Core Data store. The updateAndDelete method you suggested only works on top-level entities (`Category` in this example). 

Any ideas on how to tackle this problem are greatly appreciated!

**Comment by gonzalezreal** [comment]
You can setup a delete rule in your relationship to cascade deletes. Check the Core Data Inspector with your `items` relationship selected.

**Comment by gonzalezreal** [comment]
Sorry, I misread your question. The delete rule has no use here. In that case, the only viable solution would be to have a `deleted` field in your JSON that is mapped to your model. After processing the JSON you could perform a fetch request for all `deleted` items and remove them from the database.

**Comment by scriptease** [comment]
Thanks i use the folllowing swift version now:

    func remainingObjectsFromJSONArray<T: NSManagedObject>(array: JSONArray, inContext context: NSManagedObjectContext) throws -> [T] {
        let objects: [T] = try objectsFromJSONArray(array, inContext:context)
    
        let entity = T.entityInManagedObjectContext(context)
        
        let fetchRequest = NSFetchRequest(entityName: entity.name!);
        fetchRequest.predicate = NSPredicate(format: "NOT (self IN %@)", objects);
        fetchRequest.includesPropertyValues = false; // We just need the object IDs
    
        let deleteRequest = NSBatchDeleteRequest(fetchRequest: fetchRequest)
        try context.executeRequest(deleteRequest)
    
        return objects
    }
