### ISSUE TITLE
Introduce `identityProperties` over `identityProperties ` annotation

### ISSUE THREAD

**Issue by fabiomassimo** [gonzalezreal/Groot#60]
In my Data Model I have an entity A that has a relationship one-to-many to entity B.
When implementing the proper `userInfo` keys for B I'd like to use as `identityAttributes` a combination of an attribute in B and an attribute in A (for which B has an inverse relationship), such that I can uniquely identify an object in B for every unique object A.

Wouldn't it be better to use `propertyByName` instead of `attributeByName` to match the values that uniquely identifies an entity?
It could be something like `identityProperties` that gives the opportunity to also include attributes within other objects in a relationship.

**Comment by gonzalezreal** [comment]
I am not sure if that is even possible to accomplish. Will have a look into it.

**Comment by fabiomassimo** [comment]
Thanks for your reply.
Can I ask your opinion about this small update in my fork?
The idea is that when `Groot` tries to set a relationship, by serializing a JSON object, the relationship is preserved to make sure only objects in the relationship are updated. 

Thank you for your time.

https://github.com/fabiomassimo/Groot/commit/1ab1484b4490b55b53286196de1f7a17cf2592a4
