### ISSUE TITLE
Error on header file when compiling for swift using cocoapods.

### ISSUE THREAD

**Issue by kikolobo** [gonzalezreal/Groot#61]
**Error:** _Include of none-modular header inside framework module._
 
I get an error on a header file every time I install from cocoa pods in a swift project.

I followed to the letter the install process, however I am getting the following errors. I have to unlock the header files and comment the import statements.

<img width="1135" alt="screen shot 2016-03-08 at 12 52 40 am" src="https://cloud.githubusercontent.com/assets/368001/13594285/b947cc98-e4c8-11e5-8495-70f139c81cd0.png">

Thank you for this library. We use it often!

**Comment by gonzalezreal** [comment]
Hi, this is a Cocoapods issue. Please check #55 for possible workarounds.
