### ISSUE TITLE
possible to use managed the object's 'objectID' as a JSONKeyPath?

### ISSUE THREAD

**Issue by amitailanciano** [gonzalezreal/Groot#63]
I do not have an explicit `id` field in any of my core data entities, but I would like to have a unique identifier for serialization -- in my application I use the NSManagedObject objectID property as the unique identifier, is it possible to have Groot serialize it along with the rest of my fields?

**Comment by gonzalezreal** [comment]
Sorry, this is not possible at the moment.

**Comment by ltblueberry0** [comment]
this would be a really nice feature for existing projects which want to adopt Groot. what prevents this from being implemented?
@gonzalezreal

**Comment by gonzalezreal** [comment]
There is nothing that prevents this for being implemented. IMHO is a little bit out of scope, but perfectly possible to do it. To be honest, I don't have much time these days, so any PR is welcome, as long as the new functionality is backwards compatible, explicitly opt-in and covered by unit tests.

**Comment by ltblueberry0** [comment]
thank you for your reply! I decided to use my own UUID because the problem with the objectID is that it might change.
