### ISSUE TITLE
Private headers

### ISSUE THREAD

**Issue by faviomob** [gonzalezreal/Groot#64]
I'm building framework on top of Groot, and I use methods declared in its private headers. While I used CocoaPods I could include them directly, although this is dirty of-course. Now I've migrated to Carthage, and I can't include them anymore except directly copying them to my project. May be move them to public?
"grt_identityAttributes" method is very handy!

NSEntityDescription+Groot.h
NSPropertyDescription+Groot.h

**Comment by gonzalezreal** [comment]
Sure. Feel free to make a PR with the changes.
