### ISSUE TITLE
How To Value Transformers?

### ISSUE THREAD

**Issue by kikolobo** [gonzalezreal/Groot#7]
Can you give us an example of how to use value transformers for say an NSDate coming with "yyyy-MM-dd'T'HH:mm:ssZ" format from/to the server.

I saw in the documents that it's an attribute you set in the inspector, however how and where do I add the actual value transformer ?? In the model class or ???

**Comment by gonzalezreal** [comment]
Groot 1.0 provides an even nicer way to create [value transformers](https://github.com/gonzalezreal/Groot/blob/master/Documentation/Annotations.md#jsontransformername).

**Comment by alexeybolv** [comment]
But where to add this code?

[NSValueTransformer grt_setValueTransformerWithName:@"StringToInteger" transformBlock:^id(NSString *value) {
    return @([value integerValue]);
} reverseTransformBlock:^id(NSNumber *value) {
    return [value stringValue];
}];
