### ISSUE TITLE
How to serialize back to JSON only some properties of a NSManaged object.

### ISSUE THREAD

**Issue by kikolobo** [gonzalezreal/Groot#8]
Hi,

Is there a way for Groot to serialize back to JSON Dictionary only some properties of my NSManaged Object?

Also, I want to know if it's possible to serialize from JSON some properties and to not serial back to JSON all of those properties. For example the createdAt time stamp that is created by the server.

**Comment by gonzalezreal** [comment]
In Groot 1.0, attributes and relationships that don't have a `JSONKeyPath` entry are not considered for JSON serialization or deserialization.

This should solve your issue when serializing back to JSON.
